DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Resepti CASCADE;
DROP TABLE IF EXISTS Ainesosa CASCADE;
DROP TABLE IF EXISTS Ainesosaliitos CASCADE;

DROP TABLE IF EXISTS UserAccount CASCADE;
DROP TABLE IF EXISTS DrinkRecipe CASCADE;
DROP TABLE IF EXISTS Ingredient CASCADE;